-- Migration: Add category column to tags table and populate with categories
-- This migration adds a 'category' column to the tags table and updates all existing tags
-- with their correct category based on the tag-categories.csv file

-- Add category column to tags table
ALTER TABLE tags ADD COLUMN IF NOT EXISTS category VARCHAR(100);

-- Create index on category for faster filtering
CREATE INDEX IF NOT EXISTS idx_tags_category ON tags(category);

-- Update tags with their categories
UPDATE tags SET category = 'Couple' WHERE name = '1v1';
UPDATE tags SET category = 'Giới tính' WHERE name = 'A x A';
UPDATE tags SET category = 'Giới tính' WHERE name = 'A x B';
UPDATE tags SET category = 'Giới tính' WHERE name = 'A x O';
UPDATE tags SET category = 'Giới tính' WHERE name = 'ABO';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'App';
UPDATE tags SET category = 'Giới tính' WHERE name = 'B x A';
UPDATE tags SET category = 'Giới tính' WHERE name = 'B x B';
UPDATE tags SET category = 'Giới tính' WHERE name = 'B x O';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Bao dưỡng';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Biến thái';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Biệt nữu';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Báo thù';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Bình bộ thanh vân';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Bình dân sinh hoạt';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Bình phàm';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Bình tĩnh';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Băng sơn';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Bạch liên hoa';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Bạch nguyệt quang';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Bạch thiết hắc';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Bạn cùng phòng';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Bầu trước yêu sau';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Bệnh kiều';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Bệnh mỹ nhân';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Bộ đội đặc chủng';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Cao lãnh chi hoa';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Cao nhân lưu';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Chim hoàng yến';
UPDATE tags SET category = 'Couple' WHERE name = 'Chim hoàng yến công';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Chiếm hữu dục';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Chính kịch';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Chó săn';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Chạy nạn';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Chậm nhiệt';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Chế phục tình duyên';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Chế tác';
UPDATE tags SET category = 'Thời không' WHERE name = 'Chết đi sống lại';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Chủ bá';
UPDATE tags SET category = 'Thị giác tác phẩm' WHERE name = 'Chủ công';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Chủ cốt truyện';
UPDATE tags SET category = 'Couple' WHERE name = 'Chủ phó';
UPDATE tags SET category = 'Thị giác tác phẩm' WHERE name = 'Chủ thụ';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Chức nghiệp tinh anh';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Chức trường';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Chữa lành';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Con nuôi';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Cong bẻ thẳng';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Cthulhu';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Cung đình hầu tước';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Cung đấu';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Cuốn vương';
UPDATE tags SET category = 'Thế giới' WHERE name = 'Cyberpunk';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Cá mặn';
UPDATE tags SET category = 'Couple' WHERE name = 'Có phản công';
UPDATE tags SET category = 'Couple' WHERE name = 'Công chuyển thụ';
UPDATE tags SET category = 'Couple' WHERE name = 'Công cúc ko khiết';
UPDATE tags SET category = 'Couple' WHERE name = 'Công dưa ko khiết';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Công lược nhiệm vụ';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Công sinh con';
UPDATE tags SET category = 'Couple' WHERE name = 'Công ysl';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Cơ giáp';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Cơ trí';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Cưới trước yêu sau';
UPDATE tags SET category = 'Couple' WHERE name = 'Cường cường';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Cường giả trở về';
UPDATE tags SET category = 'Couple' WHERE name = 'Cường nhược';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Cường thủ hào đoạt';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Cưỡng chế ái';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Cải trang giả dạng';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Cấm dục';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Cấp trên cấp dưới';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Cầm tù';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Cẩu huyết';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Cận thủy lâu đài';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Cắt miếng';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Cố chấp';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Cổ võ';
UPDATE tags SET category = 'Thời không' WHERE name = 'Cổ xuyên kim';
UPDATE tags SET category = 'Thời không' WHERE name = 'Cổ đại xuyên tươg lai';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Cứu rỗi';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Cứu thế lưu';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Cực phẩm';
UPDATE tags SET category = 'Thị giác tác phẩm' WHERE name = 'Diễn đàn thể';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Duy ngã độc pháp';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Duyên trời tác hợp';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Dân bản xứ';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Dũng giả';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Dương quang';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Dưỡng oa';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Dưỡng thành';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Dạy dỗ';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Dấm vương';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Dị năng';
UPDATE tags SET category = 'Thế giới' WHERE name = 'Dị thế';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Dốc lòng';
UPDATE tags SET category = 'Giới tính' WHERE name = 'E x A';
UPDATE tags SET category = 'Giới tính' WHERE name = 'E x B';
UPDATE tags SET category = 'Giới tính' WHERE name = 'E x O';
UPDATE tags SET category = 'Giới tính' WHERE name = 'EABO';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Fork&Cake';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Gia chủ';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Giang hồ ân oán';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Giám bảo';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Giáo bá';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Giáo thảo';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Giáo viên';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Giả heo ăn hổ';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Giả tưởng sinh vật';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Giải mã';
UPDATE tags SET category = 'Couple' WHERE name = 'Giẻ lau';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Giới giải trí';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Giới giải trí Hàn';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Giới giải trí Mỹ';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Giới giải trí Nhật';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Giới thời trang';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Group chat';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Gương vỡ không lành';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Gương vỡ lại lành';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Hiện thực';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Hoa Hạ cực đoan';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Hoan hỉ oan gia';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Hoàng tử';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Hoàng đế xuyên việt';
UPDATE tags SET category = 'Thời không' WHERE name = 'Hoán đổi linh hồn';
UPDATE tags SET category = 'Couple' WHERE name = 'Huynh đệ';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Hài hước';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Hào môn thế gia';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Hòa thượng';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Hạ khắc thượng';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Hải vương';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Hắc bang';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Hắc hóa';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Hắc liên hoa';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Hắc thủ lưu';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Hắc ám';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Hằng ngày';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Hệ thống';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Họa sĩ';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Học bá';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Học viện quý tộc';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Hỏa táng tràng';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Hồng Kông';
UPDATE tags SET category = 'Thế giới' WHERE name = 'Hồng hoang';
UPDATE tags SET category = 'Couple' WHERE name = 'Hỗ công';
UPDATE tags SET category = 'Couple' WHERE name = 'Hỗ thụ';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Hợp thành';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Jack Sue';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Khoa cử';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Khuyết tật';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Khuê mật';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Không bàn tay vàng';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Không hệ thống';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Khế ước tình nhân';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Khốc ca';
UPDATE tags SET category = 'Đánh giá' WHERE name = 'Kim Bảng 🏆';
UPDATE tags SET category = 'Đánh giá' WHERE name = 'Kim bài đề cử 🥇';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Kim chủ';
UPDATE tags SET category = 'Couple' WHERE name = 'Kim chủ thụ';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Kiếp trước kiếp này';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Kiều khí';
UPDATE tags SET category = 'Couple' WHERE name = 'Kế phụ';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Kỹ thuật lưu';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Linh dị thần quái';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Linh khí sống lại';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Linh tuyền';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Liên hôn';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Liếm cẩu';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Long Ngạo Thiên';
UPDATE tags SET category = 'Couple' WHERE name = 'Loạn luân';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Luyến tổng';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Luyến ái não';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Làm giàu';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Làn đạn';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Lâu ngày gặp lại';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Lâu ngày sinh tình';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Lính gác dẫn đường';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Lôi';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Lĩnh chủ';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Lưu manh';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Lưu đày';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Lịch sử';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Lịch sử giả tưởng';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Lữ hành';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Ma pháp';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Ma quỷ';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Main là hệ thống';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Main là thực vật';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Main là đồ vật';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Main là động vật';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Mang bầu chạy';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Mang bầu không chạy';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Manh bảo';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Manh sủng';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Mary Sue';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Mua cổ văn';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Muộn tao';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Mạo hiểm';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Mất mà tìm lại';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Mất trí nhớ';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Mặt dày';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Mị ma';
UPDATE tags SET category = 'Couple' WHERE name = 'Mỹ công';
UPDATE tags SET category = 'Couple' WHERE name = 'Mỹ cường';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Mỹ cường thảm';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Mỹ nhân';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Mỹ nhân ngư';
UPDATE tags SET category = 'Couple' WHERE name = 'Mỹ thụ';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Mỹ thực';
UPDATE tags SET category = 'Couple' WHERE name = 'NP';
UPDATE tags SET category = 'Couple' WHERE name = 'NP toàn khiết 🕊️';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'NPC';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'NTR';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Nam giả nữ trang';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Nam mụ mụ';
UPDATE tags SET category = 'Thế giới' WHERE name = 'Nam nam thế giới';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Nam phụ';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Nam sủng';
UPDATE tags SET category = 'Couple' WHERE name = 'Nam sủng công';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Nghe hiểu thực vật';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Nghe hiểu động vật';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Nghiên cứu khoa học';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Nghịch tập';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Ngoại tinh sinh vật';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Ngu ngốc';
UPDATE tags SET category = 'Thế giới' WHERE name = 'Nguyên thủy';
UPDATE tags SET category = 'Đánh giá' WHERE name = 'Ngân bài đề cử 🥈';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Ngây thơ';
UPDATE tags SET category = 'Thị giác tác phẩm' WHERE name = 'Ngôi thứ ba';
UPDATE tags SET category = 'Thị giác tác phẩm' WHERE name = 'Ngôi thứ nhất';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Ngôn linh';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Người chơi';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Người qua đường';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Ngược luyến';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Ngược tra';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Ngạo kiều';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Ngọt sủng';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Ngốc manh';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Ngỗ tác';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Ngộ tính';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Ngự thú';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Ngựa giống';
UPDATE tags SET category = 'Couple' WHERE name = 'Nhiều CP';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Nhiệt huyết';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Nhiệt liệt';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Nhu nhược';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Nhân phu';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Nhân thê';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Nhân vật 2D';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Nhân vật thức tỉnh';
UPDATE tags SET category = 'Couple' WHERE name = 'Nhược công';
UPDATE tags SET category = 'Couple' WHERE name = 'Nhược cường';
UPDATE tags SET category = 'Couple' WHERE name = 'Nhược nhược';
UPDATE tags SET category = 'Couple' WHERE name = 'Nhược thụ';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Nhất kiến chung tình';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Nhẹ nhàng';
UPDATE tags SET category = 'Couple' WHERE name = 'Niên hạ';
UPDATE tags SET category = 'Couple' WHERE name = 'Niên thượng';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Niên đại văn';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Nương pháo';
UPDATE tags SET category = 'Couple' WHERE name = 'Nữ cường';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Nữ trang đại lão';
UPDATE tags SET category = 'Couple' WHERE name = 'Nữ vương thụ';
UPDATE tags SET category = 'Giới tính' WHERE name = 'O x A';
UPDATE tags SET category = 'Giới tính' WHERE name = 'O x B';
UPDATE tags SET category = 'Giới tính' WHERE name = 'O x O';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'OOC';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Oa tổng';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Otome';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'PTSD';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'PUA';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Phi nhân loại';
UPDATE tags SET category = 'Couple' WHERE name = 'Phi song khiết 🌂';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Phong lưu';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Phong thủy';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Phàm nhân lưu';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Phá án';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Pháo hôi';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Pháo hữu';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Pháp y';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Phát sóng trực tiếp';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Phúc hắc';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Phương Tây';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Phản anh hùng';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Phản bàn tay vàng';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Phản kịch bản';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Phản phái trọng sinh';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Phản phái xuyên việt';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Phản sát hệ thống';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Phật hệ';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Phế sài lưu';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Phổ nam';
UPDATE tags SET category = 'Couple' WHERE name = 'Phụ tử';
UPDATE tags SET category = 'Thời không' WHERE name = 'Qua lại thời không';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Quy tắc quái đàm';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Quyền mưu';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Quyền thần';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Quân giáo';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Quân văn';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Quản gia';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Quần tượng văn';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Quốc lộ văn';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Rút thăm trúng thưởng';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'SM';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Sa điêu';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Sang phi tất cả';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Si hán';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Si tình';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Sinh con';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Song JJ';
UPDATE tags SET category = 'Couple' WHERE name = 'Song chết';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Song hướng yêu thầm';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Song hệ thống';
UPDATE tags SET category = 'Couple' WHERE name = 'Song khiết 🕊️';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Song sinh';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Song thế thân';
UPDATE tags SET category = 'Thị giác tác phẩm' WHERE name = 'Song thị giác';
UPDATE tags SET category = 'Thời không' WHERE name = 'Song trọng sinh';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Song tính';
UPDATE tags SET category = 'Thời không' WHERE name = 'Song xuyên';
UPDATE tags SET category = 'Thế giới' WHERE name = 'Steampunk';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Sáng thế lưu';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Sát thủ';
UPDATE tags SET category = 'Couple' WHERE name = 'Sư tôn công';
UPDATE tags SET category = 'Couple' WHERE name = 'Sư đồ';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Sản nhũ';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Sảng văn';
UPDATE tags SET category = 'Couple' WHERE name = 'Sửu công';
UPDATE tags SET category = 'Couple' WHERE name = 'Sửu thụ';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Sự nghiệp não';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Tam giáo cửu lưu';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Tam quan bất chính';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Tang thi';
UPDATE tags SET category = 'Thời không' WHERE name = 'Thai xuyên';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Tham tài';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Tham ăn';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Thanh lãnh';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Thanh mai trúc mã';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Thanh thủy văn';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Thi đấu cạnh kỹ';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Thiên chi kiêu tử';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Thiên nhiên hắc';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Thiên tai';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Thiên tài';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Thuần thịt';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Thái giám giả';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Thái giám thật';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Thái y';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Thánh mẫu';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Thánh tử';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Tháo hán';
UPDATE tags SET category = 'Thời không' WHERE name = 'Thân xuyên';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Thôi miên';
UPDATE tags SET category = 'Thế giới' WHERE name = 'Thú nhân';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Thú x Người';
UPDATE tags SET category = 'Couple' WHERE name = 'Thúc chất';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Thăng cấp lưu';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Thương thành';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Thấu thị';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Thần hào lưu';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Thần minh';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Thần thoại';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Thần tiên yêu quái';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Thật giả thiếu gia';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Thẳng bẻ cong';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Thẻ bài';
UPDATE tags SET category = 'Thế giới' WHERE name = 'Thế giới song song';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Thế gả';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Thế thân';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Thể chất may mắn';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Thể thao';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Thố ti hoa';
UPDATE tags SET category = 'Thời không' WHERE name = 'Thời Chiến Quốc';
UPDATE tags SET category = 'Thời không' WHERE name = 'Thời Xuân Thu';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Thời xưa phong';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Thợ code';
UPDATE tags SET category = 'Couple' WHERE name = 'Thụ cao hơn công';
UPDATE tags SET category = 'Couple' WHERE name = 'Thụ chuyển công';
UPDATE tags SET category = 'Couple' WHERE name = 'Thụ cúc ko khiết';
UPDATE tags SET category = 'Couple' WHERE name = 'Thụ dưa ko khiết';
UPDATE tags SET category = 'Couple' WHERE name = 'Thụ tráng hơn công';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Thực tế ảo';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Tinh linh';
UPDATE tags SET category = 'Thế giới' WHERE name = 'Tinh tế';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Tiên tri';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Tiến hóa';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Tiểu bạch văn';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Tiểu nhân vật';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Tiểu tam';
UPDATE tags SET category = 'Couple' WHERE name = 'Tiện công';
UPDATE tags SET category = 'Couple' WHERE name = 'Tiện thụ';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Tool mô phỏng';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Toàn dân lưu';
UPDATE tags SET category = 'Couple' WHERE name = 'Tra công';
UPDATE tags SET category = 'Couple' WHERE name = 'Tra công tiện thụ';
UPDATE tags SET category = 'Couple' WHERE name = 'Tra công tra thụ';
UPDATE tags SET category = 'Couple' WHERE name = 'Tra thụ';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Triệu hoán lưu';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Trung khuyển';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Trung nhị';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Truyện cổ tích';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Trà xanh';
UPDATE tags SET category = 'Couple' WHERE name = 'Tráng công';
UPDATE tags SET category = 'Couple' WHERE name = 'Tráng thụ';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Trâu già gặm cỏ non';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Trò chơi';
UPDATE tags SET category = 'Thế giới' WHERE name = 'Trò chơi xâm lấn';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Trùm cuối';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Trùng tộc';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Trưởng thành';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Trạch nam';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Trạch đấu';
UPDATE tags SET category = 'Thời không' WHERE name = 'Trọng sinh';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Trộm mộ';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Tu chân';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Tu la tràng';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Tàn tật';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Tác giả';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Tái hôn';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Tâm cơ';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Tây huyễn';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Tình bạn';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Tình hữu độc chung';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Tình thân';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Tình địch';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Tông chủ';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Tùy thân không gian';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Tĩnh Khang chi sỉ';
UPDATE tags SET category = 'Thời không' WHERE name = 'Tương lai xuyên cổ đại';
UPDATE tags SET category = 'Thời không' WHERE name = 'Tương lai xuyên hiện đại';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Tương ái tương sát';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Tế thuỷ trường lưu';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Tổng nghệ';
UPDATE tags SET category = 'Couple' WHERE name = 'Tổng tài thụ';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Từ giả thành thật';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Từ hôn';
UPDATE tags SET category = 'Couple' WHERE name = 'Tự công tự thụ';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Tự ti';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Vai phụ trọng sinh';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Vai phụ xuyên việt';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Vampire';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Viết văn';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Vu cổ';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Vô hiệu hóa';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Vô hạn lưu';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Vô tình';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Vô địch lưu';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Võng du';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Võng hồng';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Võng phối';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Văn nghệ';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Văn nhã bại hoại';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Vườn trường';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Vạn người ngại';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Vạn nhân mê';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Vả mặt';
UPDATE tags SET category = 'Thời không' WHERE name = 'Vị diện';
UPDATE tags SET category = 'Thời không' WHERE name = 'Xuyên chậm';
UPDATE tags SET category = 'Thời không' WHERE name = 'Xuyên game';
UPDATE tags SET category = 'Thời không' WHERE name = 'Xuyên nhanh';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Xuyên thành vai chính';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Xuyên thành vai ác';
UPDATE tags SET category = 'Thời không' WHERE name = 'Xuyên thư';
UPDATE tags SET category = 'Thời không' WHERE name = 'Xuyên việt';
UPDATE tags SET category = 'Thời không' WHERE name = 'Xuyên về thế giới cũ';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Xúc tu';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Xướng kỹ';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Y thuật';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Ác độc';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Áo choàng lưu';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Ô nhiễm vật';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Ôn nhu';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Ăn chơi trác táng';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Ăn dưa văn';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Ăn nhờ ở đậu';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Đa nhân cách';
UPDATE tags SET category = 'Thị giác tác phẩm' WHERE name = 'Đa thị giác';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Điên phê';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Điệp viên';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Đoàn sủng';
UPDATE tags SET category = 'Xu hướng' WHERE name = 'Đoàn đội lưu';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Đoản văn';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Đánh dấu';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Đô thị tình duyên';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Đơn hướng yêu thầm';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Đơn nguyên văn';
UPDATE tags SET category = 'Giới tính' WHERE name = 'Đơn tính';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Đại lão';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Đạo tặc';
UPDATE tags SET category = 'Huyền huyễn' WHERE name = 'Đấu khí';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Đặc công';
UPDATE tags SET category = 'NV vào vai' WHERE name = 'Đế vương';
UPDATE tags SET category = 'Bối cảnh' WHERE name = 'Đệ tứ thiên tai';
UPDATE tags SET category = 'Bàn tay vàng' WHERE name = 'Đọc tâm';
UPDATE tags SET category = 'Thị giác tác phẩm' WHERE name = 'Đối thoại thể';
UPDATE tags SET category = 'Mối quan hệ' WHERE name = 'Đối thủ sống còn';
UPDATE tags SET category = 'Lĩnh vực' WHERE name = 'Đổ thạch';
UPDATE tags SET category = 'Couple' WHERE name = 'Đổi công';
UPDATE tags SET category = 'Couple' WHERE name = 'Đổi người yêu';
UPDATE tags SET category = 'Couple' WHERE name = 'Đổi thụ';
UPDATE tags SET category = 'Nhân thiết' WHERE name = 'Độc miệng';
UPDATE tags SET category = 'Phong cách' WHERE name = 'Ấm áp';

-- Set default category for any uncategorized tags
UPDATE tags SET category = 'Khác' WHERE category IS NULL;

-- Make category column NOT NULL after setting defaults
ALTER TABLE tags ALTER COLUMN category SET NOT NULL;

-- Add comment to the column
COMMENT ON COLUMN tags.category IS 'Category of the tag for organization and filtering';
